### ISSUE TITLE
Repository is too large due to PAPERS

### ISSUE THREAD

**Issue by Ueland** [SecUpwN/Android-IMSI-Catcher-Detector#213]
I was sitting here trying to get the project up and going in Android Studio when did some silly things decided to delete my local copy and check it out again. (user error). I then noticed that the repository is "gigantic" when you consider how small the project is

Why is the repo full of pdf documents where some are over 20MB each? I see that it is interesting documents but it do not think that a Github repository is the correct place for such content. [Github also mentions that you should try to limit just that](https://help.github.com/articles/working-with-large-files/), and [they have a 1GB repository size] (https://help.github.com/articles/what-is-my-disk-quota/)

This is status after **40 minutes of cloning**:
"Receiving objects:  94% (5761/6103), 142.21 MiB | 46 KiB/s" (Github is incredibly slow now :-1: )

**Comment by SecUpwN** [comment]
I am aiming at solving this Issue within the next 3 days. @He3556, have you seen the [pricing of BOX](https://www.box.com/de_DE/pricing/)? I guess those specs are too limiting for free users.

Personally, I have one more problem with that service: Their [Privacy Policy](https://www.box.com/legal/privacypolicy/) tells that they log **every single access** and they're handing it out to governments:

>**Compliance with Laws:** We may disclose your information to a third party if (a) we believe that disclosure is reasonably necessary to comply with any applicable law, regulation, legal process or governmental request, (b) to enforce our agreements, policies and Terms of Service, (c) to protect the security or integrity of the Box Services, (d) to protect Box, our customers or the public from harm or illegal activities, or (e) to respond to an emergency which we believe in the good faith requires us to disclose information to assist in preventing the death or serious bodily injury of any person.

The more I think about, I feel replacing our folder `PAPERS` with a file called `PAPERS.md` and just linking to the appropriate files with a short description would be the best solution to this. Feel free to recommend me any other online services, preferably with better access rates and higher security on personal data.

**Comment by E3V3A** [comment]
I think you should just start a new repo **here** and put it all in there and forget about it.

**Comment by Ueland** [comment]
Sorry, not fixed yet :)

thu@delta:~$ du -hs Android-IMSI-Catcher-Detector/
225M    Android-IMSI-Catcher-Detector/


The papers needs to be purged from history, i can look into it if wanted.

**Comment by SecUpwN** [comment]
@Ueland, thanks for telling me, you're doing an awesome job maintaining your Issues! Yes, please have a look into this and tell me how exactly to purge the directory from history to delete the size.

**Comment by E3V3A** [comment]
@SecUpwN  Where is that? Also, please remove or replace "/" from the file names as that messes up some non-UTF-16 command line things... E.g. "A5/3" becomes "A5-3" and so on.

**Comment by SecUpwN** [comment]
>Where is that?

@E3V3A, if you would have looked at the commit, you'd have noticed it is [here](https://spideroak.com/browse/share/AIMSICD/GitHub/PAPERS/). :smiley_cat:

>The papers needs to be purged from history, i can look into it if wanted.

I have locally rebased the project. Is there a way to update all forks that we have on GitHub?

**Comment by SecUpwN** [comment]
@Ueland, with the awesome and very detailled help of @dalibor I was able to purge the leftovers of `PAPERS` and clean up our repository. Please verify if it is working, you very likely have to delet your old fork and create a fresh one since all history has been cleaned as well. Should be solved for good now.

**Comment by Ueland** [comment]
hmm, i nuked my fork and re-forked it now, still getting the same size here.

**Comment by dalibor** [comment]
@SecUpwN @Ueland Looks like it's not cleaned up yet, because of the tags.

Here's what I did to clean it up completely:

1. I forked the [repo](https://github.com/dalibor/Android-IMSI-Catcher-Detector) on my Github account.
2. I cloned the repo locally.

```bash
$ git clone git@github.com:dalibor/Android-IMSI-Catcher-Detector.git
```

3. Checked the size:

```bash
$ cd Android-IMSI-Catcher-Detector/
$ du -sh .
225M	.
```

4. Removed PAPERS/*.pdf

```bash 
$ git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch PAPERS/*.pdf' --prune-empty --tag-name-filter cat -- --all
```

5. Cleanup of "unused" git objects

```bash
$ git for-each-ref --format='delete %(refname)' refs/original | git update-ref --stdin
$ git reflog expire --expire=now --all
$ git gc --prune=now
```

6. Check size

```bash
$ du -sh .
35M	.
```

7. Force push branches and tags

```bash
git push origin --force --all
git push origin --force --tags
```

8. Clone again

```bash
$ git clone git@github.com:dalibor/Android-IMSI-Catcher-Detector.git
```

9. Checked the size again:

```bash
$ cd Android-IMSI-Catcher-Detector/
$ du -sh .
35M	.
```

That should do it.

**Note**: Please check if [my fork](https://github.com/dalibor/Android-IMSI-Catcher-Detector) has all the files you need before doing these steps.

**Comment by SecUpwN** [comment]
Darn it, how shitty can this whole thing get? I feel like we're fucking up our whole project with this, @E3V3A. Now how about the tagged releases + APK, will the MD5 sum change as well now, @dalibor?

I have checked your fork and it seems to be fine. Executed above steps and pushed that to GitHub. You really **deserve** that credit in our `CREDIT` file, man. Happy to have see a funky guy like you here.

@Ueland and @dalibor, please check if this Issue is fixed for good now and then close it. Thank you.

**Comment by SecUpwN** [comment]
Darn it, how shitty can this whole thing get? I feel like we're fucking up our whole repository with this, @E3V3A. Now how about the tagged releases + APK, will the MD5 sum change as well now, @dalibor?

    Note: Please check if my fork has all the files you need before doing these steps.

I have checked your fork and everything appears to be fine. The only thing that prevents me now from pushing to GitHub is this error (likely due to the fact I have not set up SSH keys):

```
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/SecUpwN/Android-IMSI-Catcher-Detector.git/'
```

Is there any way around it using SmartGit or another command via terminal? I hate this SSH stuff..

**Comment by dalibor** [comment]
Yeah, MD5 sum will change because of content changes. You just need to update the MD5 sums if you're referencing the releases from somewhere.

**Comment by SecUpwN** [comment]
>Yeah, MD5 sum will change because of content changes.

Let me get this clear for myself and @E3V3A: If someone is now grabbing our project from a certain tag (like say [v0.1.25-alpha-b6](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/tree/v0.1.25-alpha-b6)) and rebuilds the APK from that, the MD5 that has been posted under the APK is currently not valid any more? So we have to recompile every APK that we've released?

I don't know what all this means for our other stores like F-Droid and especially Aptoide since they verify the APK with a matching MD5 from our original repo. Gosh, this is turning into a nightmare..

**Comment by E3V3A** [comment]
I suppose the MD5 is for the already built APK and not the whole repo, in which case we can just recompile the same APK again.

**Comment by SecUpwN** [comment]
>I suppose the MD5 is for the already built APK and not the whole repo, in which case we can just recompile the same APK again.

Yes, of course. But does it make sense to recompile every APK we had and re-upload it here?
Not sure if we should do this, what do you say @He3556 and @Ueland?

**Comment by dalibor** [comment]
@SecUpwN I don't think recompiling APKs is necessary. They're not part of git history, but manually compiled and added to releases, right?

**Comment by SecUpwN** [comment]
>@SecUpwN I don't think recompiling APKs is necessary.

Thank you for quieting my mind about this, @dalibor. Was up all night because of it!

>They're not part of git history, but manually compiled and added to releases, right?

Yes, indeed. Judging from your developers perspective, are we ready to rumble again?

**Comment by Ueland** [comment]
![](http://a.fod4.com/images/GifGuide/clapping/seinfeld.gif)


Looks fixed to me! :)

**Comment by E3V3A** [comment]
After cleanup, just make sure you select "**Import Non-Android Studio Project**" when importing our re-freshed GitHub repo into Android Studio, other wise it just doesn't work. Was driving me crazy.
