### ISSUE TITLE
App doesn't quit 

### ISSUE THREAD

**Issue by E3V3A** [SecUpwN/Android-IMSI-Catcher-Detector#498]
Debug version of App doesn't quit. Need to force close it. 

This is an old bug we used to have (issue #246) and painfully managed to solve, but now it seem all this bloody "refactoring" has re-introduced it again. Or it is a side-effect of using leakcanary? 

@d-mariano You managed to solve this in the past. Any ideas?

**Comment by d-mariano** [comment]
I will take a look at this today, it has been a while since I've worked on this app; I do miss the bug eliminating, I must say.  I'll have to refork and then familiarize myself.  I'm working on some other stuff today as well, so I'll be doing this in between.

**Comment by SecUpwN** [comment]
>I will take a look at this today, it has been a while since I've worked on this app

Welcome back, @d-mariano! It's a pleasure to see you rumbling with us again. :+1:

>I do miss the bug eliminating, I must say.

Hahaha.. best sign that you love working with us! Thanks for the indirect compliment. :)

>I'll have to refork and then familiarize myself.

Let me know if you need anything, I'll be around.

**Comment by d-mariano** [comment]
Initially I noticed a memory leak with mProgressBar, this doesn't seem to happen anymore.  Now when I quit, some seconds later LeakCanary says that the DrawerMenuAdapter causes a leak.  I'm still trying to figure this out.  I'm also looking into the issue of trying to quit the app after install, which won't work until you try it again a second time.  Can anyone confirm this behavior?

**Comment by SecUpwN** [comment]
>Can anyone confirm this behavior?

@d-mariano, I *cannot* confirm that it needed *two* tries to install our app, for me the current one just installed and runs fine. Regarding the laks, I can confirm all of the above and have collected numerous leaks in more than a week. Would it help you if upload a `.zip` file with the dumps and send it to you via email at your discretion?

**Comment by d-mariano** [comment]
What I meant was that after a fresh install, I selected "Quit" on the drawer and the icon was still present on that status bar after the app appeared to have closed.  After selecting the icon or opening up the app again, I selected "Quit" a second time and the icon disappeared from the status bar after the app closed.  Also, please send me the .zip, it may help.  

After changing line 39 in DrawerMenuAdapter.java from:
````java
this.context = context;
````
To: 
````java
this.context = context.getApplicationContext()
````
I am no longer seeing a memory leak caused by DrawerMenuAdapter.  I am, however, seeing one originate from AIMSICD.mProgressBar.  More research is to be done, I suppose.

**Comment by SecUpwN** [comment]
>I selected "Quit" a second time and the icon disappeared from the status bar after the app closed.

No matter how often I select `Quit` while having disabled the persistent service - the Icon always stays.

>I am no longer seeing a memory leak caused by DrawerMenuAdapter. I am, however, seeing one originate from AIMSICD.mProgressBar. More research is to be done, I suppose. 

Thanks for investigating my heap dumps before crafting a near PR for us. E-Mail has been sent.

**Comment by d-mariano** [comment]
It's possible the no quit is a preference issue.  My app is able to lose the icon after the second try.  I'll look more into this later.  I'm going for a run and then it might get a little late.

**Comment by DJaeger** [comment]
Try if it is solved with my PR

**Comment by SecUpwN** [comment]
>Try if it is solved with my PR

Huge thanks, but it still stays as if glued to my notification bar.

>Anyway this PR makes the code some cleaner.

Also could use more of that. A full-time code-cleaner would be awesome...

**Comment by DJaeger** [comment]
>>Try if it is solved with my PR
>
>Huge thanks, but it still stays as if glued to my notification bar.

Already seen.


It occures with activated as well with deactivated static background service and also with double back tap.

Additionally I have noticed, that with deactivated static background service the notification shortly changes to status sleeping before it quits.

This is the info for the leak on Quit from leakcanary:

```
In com.SecUpwN.AIMSICD:0.1.30-alpha-b02:30.
* com.SecUpwN.AIMSICD.AIMSICD has leaked:
* GC ROOT static com.SecUpwN.AIMSICD.AIMSICD.mProgressBar
* references android.widget.ProgressBar.mContext
* leaks com.SecUpwN.AIMSICD.AIMSICD instance

* Reference Key: 39b106d8-542c-4dda-8561-a271dcc5da1a
* Durations: watch=5301ms, gc=176ms, heap dump=792ms, analysis=15772ms

* Details:
* Class com.SecUpwN.AIMSICD.AIMSICD
|   static $staticOverhead = byte[] [id=0x41e83b81;length=24;size=40]
|   static mProgressBar = android.widget.ProgressBar [id=0x41ee2160]
* Instance of android.widget.ProgressBar
|   static $staticOverhead = byte[] [id=0x41e19e71;length=48;size=64]
|   static MAX_LEVEL = 10000
|   static TIMEOUT_SEND_ACCESSIBILITY_EVENT = 200
|   mAccessibilityEventSender = null
|   mAnimation = null
|   mTransformation = null
|   mSampleTile = android.graphics.Bitmap [id=0x41f39020]
|   mCurrentDrawable = android.graphics.drawable.LayerDrawable [id=0x41ee3470]
|   mRefreshProgressRunnable = null
|   mRefreshData = java.util.ArrayList [id=0x41ee2350]
|   mProgressDrawable = android.graphics.drawable.LayerDrawable [id=0x41ee3470]
|   mInterpolator = android.view.animation.LinearInterpolator [id=0x41ee36f8]
|   mIndeterminateDrawable = android.graphics.drawable.AnimationDrawable [id=0x4218fa08]
|   mIndeterminate = false
|   mUiThreadId = 1
|   mMaxHeight = 48
|   mMaxWidth = 144
|   mMinHeight = 48
|   mMinWidth = 144
|   mMirrorForRtl = true
|   mNoInvalidate = false
|   mOnlyIndeterminate = false
|   mProgress = 0
|   mInDrawing = false
|   mHasAnimation = false
|   mRefreshIsPosted = false
|   mDuration = 3500
|   mBehavior = 1
|   mSecondaryProgress = 0
|   mShouldStartAnimationDrawable = false
|   mAttached = false
|   mMax = 100
|   mUnsetPressedState = null
|   mAccessibilityDelegate = null
|   mUnscaledDrawingCache = null
|   mAnimator = null
|   mAttachInfo = null
|   mBackground = null
|   mTransformationInfo = null
|   mTouchDelegate = null
|   mTag = null
|   mSendViewStateChangedAccessibilityEvent = android.view.View$SendViewStateChangedAccessibilityEvent [id=0x42191198]
|   mClipBounds = null
|   mContentDescription = null
|   mContext = com.SecUpwN.AIMSICD.AIMSICD [id=0x41e84a90]
|   mCurrentAnimation = null
|   mDisplayList = android.view.GLES20DisplayList [id=0x425e2160]
|   mDrawableState = int[] [id=0x4173e9e8;length=2;size=24]
|   mDrawingCache = null
|   mSendViewScrolledAccessibilityEvent = null
|   mFloatingTreeObserver = null
|   mHardwareLayer = null
|   mScrollCache = null
|   mResources = android.content.res.XResources [id=0x41e5c250]
|   mInputEventConsistencyVerifier = null
|   mKeyedTags = null
|   mPerformClick = null
|   mPendingCheckForTap = null
|   mLayerPaint = null
|   mPendingCheckForLongPress = null
|   mLayoutInsets = null
|   mLayoutParams = android.widget.RelativeLayout$LayoutParams [id=0x42191298]
|   mParent = android.widget.RelativeLayout [id=0x41ee12f0]
|   mOverlay = null
|   mListenerInfo = null
|   mLocalDirtyRect = null
|   mMatchIdPredicate = null
|   mMatchLabelForPredicate = null
|   mMeasureCache = android.util.LongSparseLongArray [id=0x4249b6b8]
|   mMeasuredHeight = 48
|   mMeasuredWidth = 1080
|   mMinHeight = 48
|   mMinWidth = 144
|   mNextFocusDownId = -1
|   mNextFocusForwardId = -1
|   mNextFocusLeftId = -1
|   mNextFocusRightId = -1
|   mNextFocusUpId = -1
|   mOldHeightMeasureSpec = -2147481948
|   mOldWidthMeasureSpec = 1073742904
|   mOverScrollMode = 1
|   mLeftPaddingDefined = false
|   mPaddingBottom = 0
|   mPaddingLeft = 0
|   mPaddingRight = 0
|   mPaddingTop = 0
|   mLeft = 0
|   mLayerType = 0
|   mLastIsOpaque = false
|   mLabelForId = -1
|   mPrivateFlags = 16812080
|   mPrivateFlags2 = 1611867688
|   mPrivateFlags3 = 0
|   mRecreateDisplayList = false
|   mID = 2131558594
|   mRight = 1080
|   mRightPaddingDefined = false
|   mHasPerformedLongPress = false
|   mScrollX = 0
|   mScrollY = 0
|   mDrawingCacheBackgroundColor = 0
|   mCachingFailed = false
|   mSendingHoverAccessibilityEvents = false
|   mSystemUiVisibility = 0
|   mBottom = 49
|   mTop = 1
|   mBackgroundSizeChanged = true
|   mTouchSlop = 24
|   mBackgroundResource = 0
|   mTransientStateCount = 0
|   mAccessibilityViewId = 72
|   mAccessibilityCursorPosition = -1
|   mUserPaddingBottom = 0
|   mUserPaddingEnd = -2147483648
|   mUserPaddingLeft = 0
|   mUserPaddingLeftInitial = 0
|   mUserPaddingRight = 0
|   mUserPaddingRightInitial = 0
|   mUserPaddingStart = -2147483648
|   mVerticalScrollFactor = 0.0
|   mVerticalScrollbarPosition = 0
|   mViewFlags = 402653184
|   mWindowAttachCount = 1
* Instance of com.SecUpwN.AIMSICD.AIMSICD
|   static $staticOverhead = byte[] [id=0x41e83b81;length=24;size=40]
|   static mProgressBar = android.widget.ProgressBar [id=0x41ee2160]
|   TAG = java.lang.String [id=0x41e86830]
|   dbhelper = com.SecUpwN.AIMSICD.smsdetection.SmsDetectionDbHelper [id=0x4244ad28]
|   mActionBar = com.android.internal.app.ActionBarImpl [id=0x42436268]
|   mAimsicdService = com.SecUpwN.AIMSICD.service.AimsicdService [id=0x4247e900]
|   prefsEditor = null
|   mConnection = com.SecUpwN.AIMSICD.AIMSICD$5 [id=0x41e86bd8]
|   mContext = com.SecUpwN.AIMSICD.AIMSICD [id=0x41e84a90]
|   mDisclaimerAccepted = java.lang.String [id=0x424503c8]
|   mDrawerLayout = android.support.v4.widget.DrawerLayout [id=0x41ed6820]
|   mDrawerList = android.widget.ListView [id=0x42191590]
|   mDrawerTitle = java.lang.String [id=0x41e87228]
|   mDrawerToggle = com.SecUpwN.AIMSICD.AIMSICD$1 [id=0x4244c560]
|   prefs = android.app.SharedPreferencesImpl [id=0x41e75ef0]
|   mNavConf = com.SecUpwN.AIMSICD.drawer.DrawerMenuActivityConfiguration [id=0x41e9e198]
|   mTitle = java.lang.String [id=0x41e87228]
|   prefListener = com.SecUpwN.AIMSICD.AIMSICD$2 [id=0x42450388]
|   mBound = false
|   mLastPress = 0
|   mMessageReceiver = com.SecUpwN.AIMSICD.activities.BaseActivity$1 [id=0x41e86818]
|   mAllLoaderManagers = android.support.v4.util.SimpleArrayMap [id=0x4245e040]
|   mLoaderManager = null
|   mContainer = android.support.v4.app.FragmentActivity$2 [id=0x41e864b8]
|   mHandler = android.support.v4.app.FragmentActivity$1 [id=0x41e85078]
|   mFragments = android.support.v4.app.FragmentManagerImpl [id=0x41e85b80]
|   mCreated = true
|   mCheckedForLoaderManager = true
|   mLoadersStarted = false
|   mOptionsMenuInvalidated = false
|   mReallyStopped = true
|   mResumed = false
|   mRetaining = false
|   mStopped = true
|   mActionBar = com.android.internal.app.ActionBarImpl [id=0x42436268]
|   mActivityInfo = android.content.pm.ActivityInfo [id=0x41e4a728]
|   mAllLoaderManagers = android.util.ArrayMap [id=0x424535f8]
|   mApplication = com.SecUpwN.AIMSICD.AppAIMSICD [id=0x41e5d638]
|   mWindowManager = android.view.WindowManagerImpl [id=0x41e87da8]
|   mWindow = com.android.internal.policy.impl.PhoneWindow [id=0x41e87390]
|   mUiThread = java.lang.Thread [id=0x41704de0]
|   mTranslucentCallback = null
|   mComponent = android.content.ComponentName [id=0x41e4a4f0]
|   mToken = android.os.BinderProxy [id=0x41e4a6c8]
|   mContainer = android.app.Activity$1 [id=0x41e84c88]
|   mCurrentConfig = android.content.res.Configuration [id=0x41e872f0]
|   mDecor = null
|   mTitle = java.lang.String [id=0x41e87228]
|   mDefaultKeySsb = null
|   mSearchManager = null
|   mResultData = null
|   mEmbeddedID = null
|   mParent = null
|   mMenuInflater = android.view.MenuInflater [id=0x425ce390]
|   mFragments = android.app.FragmentManagerImpl [id=0x41e84c10]
|   mHandler = android.os.Handler [id=0x41e84d30]
|   mManagedDialogs = null
|   mInstanceTracker = android.os.StrictMode$InstanceTracker [id=0x41e84cb0]
|   mInstrumentation = android.app.Instrumentation [id=0x41e5d198]
|   mIntent = android.content.Intent [id=0x41e4a3f0]
|   mLastNonConfigurationInstances = null
|   mLoaderManager = null
|   mManagedCursors = java.util.ArrayList [id=0x41e84c98]
|   mMainThread = android.app.ActivityThread [id=0x41e491b8]
|   mLoadersStarted = false
|   mIdent = 1109564064
|   mFinished = true
|   mEnableDefaultActionBarUp = false
|   mResultCode = 0
|   mDoReportFullyDrawn = false
|   mResumed = false
|   mDestroyed = true
|   mStartedActivity = false
|   mStopped = true
|   mTemporaryPause = false
|   mDefaultKeyMode = 0
|   mTitleColor = 0
|   mTitleReady = true
|   mConfigChangeFlags = 0
|   mCheckedForLoaderManager = true
|   mChangingConfigurations = false
|   mVisibleFromClient = true
|   mVisibleFromServer = true
|   mChangeCanvasToTranslucent = false
|   mWindowAdded = true
|   mCalled = true
|   mBase = android.app.ContextImpl [id=0x41e86be8]
|   mInflater = com.android.internal.policy.impl.PhoneLayoutInflater [id=0x41e878f0]
|   mOverrideConfiguration = null
|   mResources = android.content.res.XResources [id=0x41e5c250]
|   mTheme = android.content.res.Resources$Theme [id=0x41e87dc0]
|   mThemeResource = 2131427328
|   mBase = android.app.ContextImpl [id=0x41e86be8]
```

**Comment by DJaeger** [comment]
Thats crazy.
I wanted to analyse this some more, but leak canary crashes :-D

**Comment by E3V3A** [comment]
@DJaeger Is there a way to temporarily comment out the leakcanary import?

**Comment by E3V3A** [comment]
Merged PR for commenting out leakcanary in lack of bug support.

**Comment by DJaeger** [comment]
This issue seems to be solved.
For me it properly quits.

Also the log is now clean without leakcanary:
```
D/AppAIMSICD(32362): BaseTask detach:com.SecUpwN.AIMSICD.AIMSICD
I/NotificationService(  740): cancelToast pkg=com.SecUpwN.AIMSICD callback=android.app.ITransientNotification$Stub$Proxy@427844f0
W/NotificationService(  740): Toast already cancelled. pkg=com.SecUpwN.AIMSICD callback=android.app.ITransientNotification$Stub$Proxy@427844f0
I/NotificationService(  740): cancelToast pkg=com.SecUpwN.AIMSICD callback=android.app.ITransientNotification$Stub$Proxy@41ea4980
W/NotificationService(  740): Toast already cancelled. pkg=com.SecUpwN.AIMSICD callback=android.app.ITransientNotification$Stub$Proxy@41ea4980
I/AIMSICD_Service(32362): Service destroyed.
```

**Comment by DJaeger** [comment]
>Initially I noticed a memory leak with mProgressBar, this doesn't seem to happen anymore.

I still could see that (sometimes) last time leakcanary worked.

>Now when I quit, some seconds later LeakCanary says that the DrawerMenuAdapter causes a leak. I'm still trying to figure this out.

This is solved.

I will look, if I can find something curios of mProgessBar.
Also I will try to solve the flashing "service is sleeping" on quit.
Should we track that here or in a new issue?

**Comment by SecUpwN** [comment]
>This issue seems to be solved.
>For me it properly quits.

For me, it unfortunately doesn't...

**Comment by d-mariano** [comment]
I haven't had much time to look back at it, but I am suspecting that the persist service preference is not saved or tested properly.  This might be a good place to look for those who do not have time.  I still experience an unsuccessful quit after a fresh install, but then when I select the remaining notification and the app is brought up again, I can successfully quit after trying a second time.  Again, this is something that seems like a preference issue.

**Comment by DJaeger** [comment]
For me all is working with current build.
Could you please give me log?

**Comment by E3V3A** [comment]
@d-mariano Have you got a Buildozer account from @SecUpwN ?

**Comment by E3V3A** [comment]
I can confirm that on Buildozer **162** (b06) it still does **not** close.

**Comment by E3V3A** [comment]
Can somebody please look at this? It's so annoying that I'm starting to hesitate to install dev builds for testing...

**Comment by DJaeger** [comment]
Please give me a catlog and I will look into.

**Comment by E3V3A** [comment]
Back button twice, works on BD b165, but drawer 'Quit' doesn't...

**Comment by E3V3A** [comment]
This should be a trivial fix, as it already works with back button. Probably the `Quit` item/button have a broken mapping.

**Comment by DJaeger** [comment]
PLEASE GIVE ME A LOGCAT THAN I CAN LOOK INTO!
You ask multiple times for solving this, but tell me how I should solve it if I do not have this issue and no one gives me a logcat!?

**Comment by E3V3A** [comment]
Well, I tried yesterday, but now the app keep crashing on start... (I'm far away from my dev PC so I can't collect logcats.)

**Comment by DJaeger** [comment]
We have a debug function in our app and you can also use "aLogcat ROOT" from F-Droid to get logcats.

**Comment by E3V3A** [comment]
Right, but because of #406 and #496 it can't be used.

**Comment by DJaeger** [comment]
The only issue that with most current build (on Buildozer failed because of internal issue) still prevents the app from starting is the one caused by lacells database, which can be workarounded by removing .nogapps directory.
To workaround the failed build you can simply let Android get a current position with another app that requests fine location and then start AIMSICD or if you are fast you can disable GPS, open AIMSICD cancel question for activating location services and and disable cell tracking from navigation drawer.

**Comment by SecUpwN** [comment]
>(on Buildozer failed because of internal issue)

Manually launched a fresh build to test latest changes.

**Comment by E3V3A** [comment]
> The only issue that with most current build (on Buildozer failed because of internal issue) still prevents the app from starting is the one caused by lacells database,

That's why I [suggested](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/496#issuecomment-118241486) and [here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/pull/467#issuecomment-118226879) that we remove all that *lacells* junk. We've wasted several weeks of debugging new issues, just because of it.

**Comment by DJaeger** [comment]
@E3V3A: Did we? Have not done so as I wanted to the other issues first, as the lacells issue was the simplest one to workaround.
I will now work on it.

**Comment by SecUpwN** [comment]
>I will now work on it.

@DJaeger, I am unbelievably thankful to have you in our team! Always remember to **take a break**.

**Comment by E3V3A** [comment]
App now (and surprisingly) quits as expected.

**Comment by E3V3A** [comment]
Hmm, still not resolved. I have no idea why it worked last time I it.

**Comment by SecUpwN** [comment]
Test results with latest build on my HTC One M7: Quit doesn't work, pressing Back-button twice does.

**Comment by E3V3A** [comment]
[Here](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/b630101ed1908e5b272e1a9eaacf6950ac25a9b7/app/src/main/java/com/SecUpwN/AIMSICD/AIMSICD.java#L551-L572)'s the code for back-button press:

```java
    public void onBackPressed() {
        Toast onBackPressedToast = Toast
                .makeText(this, R.string.press_once_again_to_exit, Toast.LENGTH_SHORT);
        long currentTime = System.currentTimeMillis();
        if (currentTime - mLastPress > 5000) {
            onBackPressedToast.show();
            mLastPress = currentTime;
        } else {
            onBackPressedToast.cancel();
            super.onBackPressed();
            try {
                if(mAimsicdService.isSmsTracking()) {
                    mAimsicdService.stopSmsTracking();
                }
            }catch (Exception ee){System.out.println("Error: Stopping SMS detection");}
            finish();
        }
    }
```
But in the `Quit` [line](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/blob/b630101ed1908e5b272e1a9eaacf6950ac25a9b7/app/src/main/java/com/SecUpwN/AIMSICD/AIMSICD.java#L373-L375) we only have:
```java
        } else if (selectedItem.getId() == DrawerMenu.ID.APPLICATION.QUIT) {
            finish();
        }
```

So maybe we need to add the following line after `finish()`? 
```
 if (mAimsicdService != null) mAimsicdService.onDestroy();
```
or something like that...

**Comment by SecUpwN** [comment]
>So maybe we need to add the following line after `finish()`?

How about if you just add it so that we can try it out, @E3V3A?

**Comment by E3V3A** [comment]
Done, please test.

**Comment by E3V3A** [comment]
Almost works. 
Now I get the pop-up saying `Unfortunately ....has stopped [OK]`...

**Comment by banjaxbanjo** [comment]
Maybe

try {
 if(mAimsicdService.isSmsTracking()) { 
     mAimsicdService.stopSmsTracking();
 }
 }catch (Exception ee){System.out.println("Error: Stopping SMS detection");
}

if (mAimsicdService != null) mAimsicdService.onDestroy();
finish();

**Comment by E3V3A** [comment]
Enabling (checking) the `Peristent Service` makes Quit behave as it should. Has the persistent Service logic become reversed again? (If it has then my fix above, probably need reversing.)

**Comment by E3V3A** [comment]
@banjaxbanjo  You mean like this??
```java
...
} else if (selectedItem.getId() == DrawerMenu.ID.APPLICATION.QUIT) {
	try {
		if(mAimsicdService.isSmsTracking()) { 
			mAimsicdService.stopSmsTracking();
		}
	}catch (Exception ee) {
		System.out.println("Error: Stopping SMS detection");
	}

	if (mAimsicdService != null) mAimsicdService.onDestroy();
	finish();
}
...
```

**Comment by banjaxbanjo** [comment]
@E3V3A Yeh that should work its basically stopping  anything that should be stopped before exit

**Comment by E3V3A** [comment]
Same problem...

**Comment by banjaxbanjo** [comment]
Weird can you see the error log?

**Comment by E3V3A** [comment]
Sorry I don't have time to fiddle with the logging today, somebody else has to look.

**Comment by banjaxbanjo** [comment]
Np I say its something simple anyway

**Comment by SecUpwN** [comment]
Interesting, https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/commit/a4a465d4b42592d46b60a38962b5e344654ec954 seems to fix this for me with Buildozer Build `#199`. Please test again, @E3V3A.

**Comment by E3V3A** [comment]
I did, same problem. Weird!

**Comment by SecUpwN** [comment]
>I did, same problem. Weird!

Fresh install?

**Comment by E3V3A** [comment]
Seems fixed after DB overhaul so Please re-test this issue now. (Using Buildozer build >= 211)

**Comment by E3V3A** [comment]
Edit:  WTF! 
Apparently now the issue has the *reverse* problem. Now the `Quit` selection in drawer menu works, but not the "back button * 2"!

**Comment by E3V3A** [comment]
BB*2 Doesn't work on first or second start, but later... Very strange.

**Comment by banjaxbanjo** [comment]
This doesn't happen on my phone quits with both methods quite strange

**Comment by E3V3A** [comment]
Actually I think it happens when the tracker and/or monitoring is already off... Need more testing.
